### ISSUE TITLE
[FEAT] 멋사 4주차 과제🦁

### ISSUE THREAD

**Issue by summit45** [Likelion-at-SMWU-10th/LeeSuMin#10]
## 📌  Feature Issue

구현해보고 싶은 웹서비스 아이디어 생각해오기

## 📝  To-do

- [ ] 나만의 웹서비스 아이디어를 설명하는 페이지 만들기
- [ ] (조건1) 프로젝트와 앱 이름 설정
- [ ] (조건2) 디자인 틀 사용X
