### ISSUE TITLE
[FEAT] 멋사 6주차 과제🦁

### ISSUE THREAD

**Issue by summit45** [Likelion-at-SMWU-10th/LeeSuMin#14]
## 📌  Feature Issue

멋사 백엔드 6주차 과제
6주차 실습 내용 토대로 나만의 다이어리 만들기

## 📝  To-do

- [ ] 프로젝트 이름, 앱 이름 다르게 사용
- [ ] 앱 2개 이상 만들어서 url mapping 사용
- [ ] static 사용해서 이미지나 css 넣기(bootstrap)
- [ ] 템플릿 언어 사용하기
