### ISSUE TITLE
[FEAT] 멋사 7주차 과제🦁

### ISSUE THREAD

**Issue by summit45** [Likelion-at-SMWU-10th/LeeSuMin#18]
## 📌  Feature Issue

'일단 만드는 Django' 코드라이언 강의 수강

## 📝  To-do

- [x] Chapter1: Intro
- [x] Chapter2: Django와 친해지기
- [x] Chapter3: [project1] 회사 소개 사이트
- [x] Chapter4: [project2-1] 개발자 대나무숲 프로젝트 준비하기
